---
apiVersion: netconf.ciena.com/v1alpha1
kind: YangMetadata
metadata:
  name: classifier-meta
  namespace: default
spec:
  reference:
    apiVersion: netconf.ciena.com/v1alpha1
    group: netconf.ciena.com
    kind: Classifier
  wrapper:
    augmentor:
      filterEntry.filterParameter: xmlns:classifier=urn:ciena:params:xml:ns:yang:ciena-pn::ciena-mef-classifier
    config: true
    keyField: name
    module: ciena-mef-classifier.yang
    moduleSearchPath: yang
    xmlName: classifier
    xmlRequestName: classifiers
